name: "Gatsby Publish"
description: "Build and deploy your Gatsby site to GitHub Pages."
branding:
  icon: "book-open"
  color: "purple"
inputs:
  site-name:
    description: "Required name of the site you are deploying to"
    required: true
  gatsby-args:
    description: "Additional arguments that get passed to `gatsby build`."
    required: false
    default: ""
  skip-publish:
    description: "Builds your Gatsby site but skips publishing by setting it to `true`. Helpful for testing/debugging Workflows."
    required: false
    default: false
runs:
  using: "node12"
  main: "./dist/index.js"
